vendor_gallery:
    resource: "@VendorGalleryBundle/Resources/config/routing.yml"
    prefix:   /
user_bundle:
    resource: "@UserBundle/Resources/config/routing.yml"
fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }